[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "center"]
set = true


[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'


[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'
